version: '3.8'

services:


  documentserver:
    image: onlyoffice/documentserver:7.3
    ports:
      - "8000:80"
    volumes:
      - ./uploads:/var/www/onlyoffice/Data
    environment:
      - JWT_ENABLED=false
      # - JWT_SECRET=your_jwt_secret_key_here
    restart: unless-stopped
    networks:
      - onlyoffice-network

networks:
  onlyoffice-network:
    driver: bridge

volumes:
  document-data:
  document-logs: